// Country to currency code mapping
export const countryCurrencyMap: Record<string, string> = {
  'United States': 'USD',
  'United Kingdom': 'GBP',
  'Canada': 'CAD',
  'Australia': 'AUD',
  'Germany': 'EUR',
  'France': 'EUR',
  'Italy': 'EUR',
  'Spain': 'EUR',
  'Netherlands': 'EUR',
  'Belgium': 'EUR',
  'Austria': 'EUR',
  'Portugal': 'EUR',
  'Ireland': 'EUR',
  'Greece': 'EUR',
  'Japan': 'JPY',
  'China': 'CNY',
  'South Korea': 'KRW',
  'India': 'INR',
  'Brazil': 'BRL',
  'Mexico': 'MXN',
  'Argentina': 'ARS',
  'Chile': 'CLP',
  'Colombia': 'COP',
  'Peru': 'PEN',
  'Russia': 'RUB',
  'Turkey': 'TRY',
  'South Africa': 'ZAR',
  'Egypt': 'EGP',
  'Nigeria': 'NGN',
  'Kenya': 'KES',
  'Morocco': 'MAD',
  'Tunisia': 'TND',
  'Saudi Arabia': 'SAR',
  'United Arab Emirates': 'AED',
  'Qatar': 'QAR',
  'Kuwait': 'KWD',
  'Bahrain': 'BHD',
  'Oman': 'OMR',
  'Jordan': 'JOD',
  'Lebanon': 'LBP',
  'Israel': 'ILS',
  'Iran': 'IRR',
  'Iraq': 'IQD',
  'Afghanistan': 'AFN',
  'Pakistan': 'PKR',
  'Bangladesh': 'BDT',
  'Sri Lanka': 'LKR',
  'Nepal': 'NPR',
  'Myanmar': 'MMK',
  'Thailand': 'THB',
  'Vietnam': 'VND',
  'Malaysia': 'MYR',
  'Singapore': 'SGD',
  'Indonesia': 'IDR',
  'Philippines': 'PHP',
  'Cambodia': 'KHR',
  'Laos': 'LAK',
  'Brunei': 'BND',
  'Taiwan': 'TWD',
  'Hong Kong': 'HKD',
  'Macau': 'MOP',
  'Mongolia': 'MNT',
  'North Korea': 'KPW',
  'Kazakhstan': 'KZT',
  'Uzbekistan': 'UZS',
  'Kyrgyzstan': 'KGS',
  'Tajikistan': 'TJS',
  'Turkmenistan': 'TMT',
  'Georgia': 'GEL',
  'Armenia': 'AMD',
  'Azerbaijan': 'AZN',
  'Belarus': 'BYN',
  'Ukraine': 'UAH',
  'Moldova': 'MDL',
  'Romania': 'RON',
  'Bulgaria': 'BGN',
  'Hungary': 'HUF',
  'Poland': 'PLN',
  'Czech Republic': 'CZK',
  'Slovakia': 'EUR',
  'Slovenia': 'EUR',
  'Croatia': 'EUR',
  'Bosnia and Herzegovina': 'BAM',
  'Serbia': 'RSD',
  'Montenegro': 'EUR',
  'North Macedonia': 'MKD',
  'Albania': 'ALL',
  'Lithuania': 'EUR',
  'Latvia': 'EUR',
  'Estonia': 'EUR',
  'Finland': 'EUR',
  'Sweden': 'SEK',
  'Norway': 'NOK',
  'Denmark': 'DKK',
  'Iceland': 'ISK',
  'Switzerland': 'CHF',
  'Liechtenstein': 'CHF',
  'Luxembourg': 'EUR',
  'Monaco': 'EUR',
  'Vatican City': 'EUR',
  'San Marino': 'EUR',
  'Andorra': 'EUR',
  'Malta': 'EUR',
  'Cyprus': 'EUR',
  'New Zealand': 'NZD',
  'Fiji': 'FJD',
  'Papua New Guinea': 'PGK',
  'Solomon Islands': 'SBD',
  'Vanuatu': 'VUV',
  'Samoa': 'WST',
  'Tonga': 'TOP',
  'Kiribati': 'AUD',
  'Tuvalu': 'AUD',
  'Nauru': 'AUD',
  'Palau': 'USD',
  'Marshall Islands': 'USD',
  'Micronesia': 'USD'
};

// Function to get currency from country name
export function getCurrencyFromCountry(countryName: string): string {
  return countryCurrencyMap[countryName] || 'USD'; // Default to USD if not found
}

// Function to get currency from destination (simplified mapping)
export function getCurrencyFromDestination(destination: string): string {
  // Extract country from destination string (e.g., "Paris, France" -> "France")
  const parts = destination.split(',').map(s => s.trim());
  
  // Try to find currency by checking each part against our mapping
  for (const part of parts.reverse()) {
    const currency = countryCurrencyMap[part];
    if (currency) return currency;
  }
  
  // Fallback mappings for common city destinations
  const cityToCurrency: Record<string, string> = {
    'New York': 'USD',
    'Los Angeles': 'USD',
    'Chicago': 'USD',
    'Miami': 'USD',
    'Las Vegas': 'USD',
    'San Francisco': 'USD',
    'London': 'GBP',
    'Paris': 'EUR',
    'Rome': 'EUR',
    'Barcelona': 'EUR',
    'Amsterdam': 'EUR',
    'Berlin': 'EUR',
    'Munich': 'EUR',
    'Vienna': 'EUR',
    'Zurich': 'CHF',
    'Geneva': 'CHF',
    'Dubai': 'AED',
    'Abu Dhabi': 'AED',
    'Doha': 'QAR',
    'Kuwait City': 'KWD',
    'Riyadh': 'SAR',
    'Cairo': 'EGP',
    'Istanbul': 'TRY',
    'Moscow': 'RUB',
    'Tokyo': 'JPY',
    'Beijing': 'CNY',
    'Shanghai': 'CNY',
    'Hong Kong': 'HKD',
    'Singapore': 'SGD',
    'Bangkok': 'THB',
    'Mumbai': 'INR',
    'Delhi': 'INR',
    'Sydney': 'AUD',
    'Melbourne': 'AUD',
    'Toronto': 'CAD',
    'Vancouver': 'CAD',
    'São Paulo': 'BRL',
    'Rio de Janeiro': 'BRL',
    'Buenos Aires': 'ARS',
    'Mexico City': 'MXN',
    'Johannesburg': 'ZAR',
    'Cape Town': 'ZAR'
  };
  
  // Check city mapping
  for (const [city, currency] of Object.entries(cityToCurrency)) {
    if (destination.toLowerCase().includes(city.toLowerCase())) {
      return currency;
    }
  }
  
  return 'USD'; // Default fallback
}